In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("All libraries imported successfully!")

All libraries imported successfully!

In [3]:
import sys
print(sys.executable)

c:\Users\hp\anaconda3\envs\regression_app\python.exe

In [4]:
import sys
!{sys.executable} -m pip install matplotlib seaborn

Requirement already satisfied: matplotlib in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (3.11.2)
Requirement already satisfied: seaborn in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (from matplotlib) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (from seaborn) (3.0.6)
Requirement already satisfied: tzdata in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (from pandas>=1.2->seaborn) (2026.5)
Requirement already satisfied: six>=1.5 in c:\Users\hp\anaconda3\envs\regression_app\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [5]:
df = pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\ADITI DATA\KPMG\UrbanKart_Customer_Analytics_Master.csv")
df.head()

,Customer_ID,Customer_Name,Age,Gender,City_Tier,Income,Customer_Tenure_Months,Acquisition_Channel,Website_Visits_Monthly,App_Sessions_Monthly,...,Payment_Delay_Count,Loyalty_Points,Marketing_Response_Rate,Annual_Revenue,Churn,Purchase_Next_30_Days,Customer_Lifetime_Value,Preferred_Category,Preferred_Channel,Customer_Value_Segment
0,CUST000001,Aryan Maharaj,23,Female,Tier 3,471173.0,54,Offline Store,8.0,12.0,...,0,119,0.017,29211.42,0,1,33024.39,Electronics,Website,Medium Value
1,CUST000002,Udant Dewan,37,Female,Tier 2,150000.0,28,Organic Search,20.0,16.0,...,0,1191,0.330,163225.27,0,0,137497.85,Electronics,Website,High Value
2,CUST000003,Gagan Sami,36,Female,Tier 2,1089061.0,18,Affiliate,9.0,12.0,...,0,973,0.229,92828.35,0,1,64319.68,Electronics,Physical Store,High Value
3,CUST000004,Ayushman Chander,40,Male,Tier 1,661655.0,11,Social Media,9.0,5.0,...,2,52,0.132,8063.92,1,0,2384.79,Grocery,Website,Low Value
4,CUST000005,Viraj Tiwari,58,Male,Tier 1,220959.0,10,Social Media,11.0,9.0,...,0,55,0.258,9955.62,0,0,4263.70,Fashion,Mobile App,Low Value

In [6]:
df.tail()

,Customer_ID,Customer_Name,Age,Gender,City_Tier,Income,Customer_Tenure_Months,Acquisition_Channel,Website_Visits_Monthly,App_Sessions_Monthly,...,Payment_Delay_Count,Loyalty_Points,Marketing_Response_Rate,Annual_Revenue,Churn,Purchase_Next_30_Days,Customer_Lifetime_Value,Preferred_Category,Preferred_Channel,Customer_Value_Segment
19995,CUST019996,Advik Sachdev,46,Female,Tier 1,499169.0,33,Offline Store,15.0,9.0,...,1,425,0.332,62862.55,0,1,64436.02,Home & Kitchen,Mobile App,High Value
19996,CUST019997,Yug Upadhyay,42,Female,Tier 1,945257.0,15,Organic Search,4.0,2.0,...,2,11,0.133,509.19,1,0,170.81,Grocery,Website,Low Value
19997,CUST019998,Priya Golla,24,Male,Tier 1,1680032.0,61,Email,7.0,15.0,...,2,131,0.223,36693.97,0,0,34248.61,Sports & Fitness,Mobile App,Medium Value
19998,CUST019999,Charita Ray,32,Male,Tier 2,312155.0,44,Referral,10.0,18.0,...,0,1460,0.024,76552.31,1,0,89562.24,Electronics,Physical Store,High Value
19999,CUST020000,Wazir Borah,25,Male,Tier 1,572246.0,17,Marketplace,4.0,3.0,...,0,61,0.000,497.18,1,0,176.98,Fashion,Physical Store,Low Value

In [7]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City_Tier', 'Income',
       'Customer_Tenure_Months', 'Acquisition_Channel',
       'Website_Visits_Monthly', 'App_Sessions_Monthly',
       'Purchase_Frequency_Monthly', 'Average_Order_Value',
       'Discount_Usage_Rate', 'Orders_Last_12M', 'Days_Since_Last_Purchase',
       'Return_Rate', 'Support_Tickets_12M', 'Customer_Satisfaction_Score',
       'Payment_Delay_Count', 'Loyalty_Points', 'Marketing_Response_Rate',
       'Annual_Revenue', 'Churn', 'Purchase_Next_30_Days',
       'Customer_Lifetime_Value', 'Preferred_Category', 'Preferred_Channel',
       'Customer_Value_Segment'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer_ID                  20000 non-null  str
 1   Customer_Name                20000 non-null  str
 2   Age                          20000 non-null  int64
 3   Gender                       20000 non-null  str
 4   City_Tier                    20000 non-null  str
 5   Income                       19400 non-null  float64
 6   Customer_Tenure_Months       20000 non-null  int64
 7   Acquisition_Channel          19600 non-null  str
 8   Website_Visits_Monthly       19300 non-null  float64
 9   App_Sessions_Monthly         19400 non-null  float64
 10  Purchase_Frequency_Monthly   20000 non-null  float64
 11  Average_Order_Value          20000 non-null  float64
 12  Discount_Usage_Rate          20000 non-null  float64
 13  Orders_Last_12M              20000 non-null  int64
 14  Days_Since_Last_Purchase     20000 non-null  int64
 15  Return_Rate                  20000 non-null  float64
 16  Support_Tickets_12M          20000 non-null  int64
 17  Customer_Satisfaction_Score  19200 non-null  float64
 18  Payment_Delay_Count          20000 non-null  int64
 19  Loyalty_Points               20000 non-null  int64
 20  Marketing_Response_Rate      19400 non-null  float64
 21  Annual_Revenue               20000 non-null  float64
 22  Churn                        20000 non-null  int64
 23  Purchase_Next_30_Days        20000 non-null  int64
 24  Customer_Lifetime_Value      20000 non-null  float64
 25  Preferred_Category           19500 non-null  str
 26  Preferred_Channel            20000 non-null  str
 27  Customer_Value_Segment       20000 non-null  str
dtypes: float64(11), int64(9), str(8)
memory usage: 4.3 MB

In [9]:
df.describe()

,Age,Income,Customer_Tenure_Months,Website_Visits_Monthly,App_Sessions_Monthly,Purchase_Frequency_Monthly,Average_Order_Value,Discount_Usage_Rate,Orders_Last_12M,Days_Since_Last_Purchase,Return_Rate,Support_Tickets_12M,Customer_Satisfaction_Score,Payment_Delay_Count,Loyalty_Points,Marketing_Response_Rate,Annual_Revenue,Churn,Purchase_Next_30_Days,Customer_Lifetime_Value
count,20000.000000,1.940000e+04,20000.000000,19300.000000,19400.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,19200.000000,20000.000000,20000.000000,19400.00000,20000.000000,20000.000000,20000.000000,20000.000000
mean,38.193900,5.921987e+05,24.061250,12.323990,13.882990,0.537693,1845.453167,0.406639,6.611900,72.452850,0.132860,0.969450,3.505293,0.813400,230.278750,0.25482,44288.260337,0.247000,0.451750,32197.683549
std,11.477238,4.353917e+05,15.600688,9.169258,10.394052,0.386064,1350.782124,0.200085,5.540155,69.246223,0.097917,1.554296,0.823314,0.975155,397.115611,0.21910,46386.761759,0.431278,0.497679,38963.674642
min,18.000000,1.500000e+05,1.000000,0.000000,0.000000,0.100000,170.560000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.00000,491.190000,0.000000,0.000000,64.760000
25%,30.000000,2.991995e+05,12.000000,6.000000,7.000000,0.280000,962.485000,0.254000,3.000000,26.000000,0.059000,0.000000,3.000000,0.000000,43.000000,0.05500,4851.805000,0.000000,0.000000,2543.910000
50%,38.000000,4.707170e+05,21.000000,10.000000,11.000000,0.440000,1464.940000,0.394000,5.000000,50.000000,0.118000,0.000000,3.610000,1.000000,106.000000,0.22400,32966.325000,0.000000,0.000000,20346.305000
75%,46.000000,7.437775e+05,32.000000,16.000000,18.000000,0.680000,2291.930000,0.550000,9.000000,94.000000,0.190000,2.000000,4.110000,1.000000,254.000000,0.40000,67364.075000,0.000000,1.000000,46801.957500
max,70.000000,5.000000e+06,72.000000,167.000000,135.000000,5.050000,27993.310000,1.000000,75.000000,365.000000,0.663000,21.000000,5.000000,8.000000,9649.000000,1.00000,513835.370000,1.000000,1.000000,466257.010000

In [10]:
df.isnull().sum()

Customer_ID                      0
Customer_Name                    0
Age                              0
Gender                           0
City_Tier                        0
Income                         600
Customer_Tenure_Months           0
Acquisition_Channel            400
Website_Visits_Monthly         700
App_Sessions_Monthly           600
Purchase_Frequency_Monthly       0
Average_Order_Value              0
Discount_Usage_Rate              0
Orders_Last_12M                  0
Days_Since_Last_Purchase         0
Return_Rate                      0
Support_Tickets_12M              0
Customer_Satisfaction_Score    800
Payment_Delay_Count              0
Loyalty_Points                   0
Marketing_Response_Rate        600
Annual_Revenue                   0
Churn                            0
Purchase_Next_30_Days            0
Customer_Lifetime_Value          0
Preferred_Category             500
Preferred_Channel                0
Customer_Value_Segment           0
dtype: int64

In [11]:
df['App_Sessions_Monthly'].head()

0    12.0
1    16.0
2    12.0
3     5.0
4     9.0
Name: App_Sessions_Monthly, dtype: float64

In [12]:
df['Income'].head() #replace with median

0     471173.0
1     150000.0
2    1089061.0
3     661655.0
4     220959.0
Name: Income, dtype: float64

In [13]:
df['Acquisition_Channel'].head()

0     Offline Store
1    Organic Search
2         Affiliate
3      Social Media
4      Social Media
Name: Acquisition_Channel, dtype: str

In [14]:
df['Website_Visits_Monthly'].head() #replace with mode

0     8.0
1    20.0
2     9.0
3     9.0
4    11.0
Name: Website_Visits_Monthly, dtype: float64

In [15]:
df['Customer_Satisfaction_Score'].head() #replace with median

0    4.29
1    3.46
2    4.14
3    1.43
4    3.91
Name: Customer_Satisfaction_Score, dtype: float64

In [16]:
df['Marketing_Response_Rate'].head() #replace with median

0    0.017
1    0.330
2    0.229
3    0.132
4    0.258
Name: Marketing_Response_Rate, dtype: float64

In [17]:
df['Preferred_Category'].head()

0    Electronics
1    Electronics
2    Electronics
3        Grocery
4        Fashion
Name: Preferred_Category, dtype: str

In [18]:
df['Income'] = df['Income'].fillna(df['Income'].median())

In [19]:
df['Income'].isnull().sum()

np.int64(0)

In [20]:
df['Preferred_Category'].isnull().sum()

np.int64(500)

In [21]:
for i in ['Customer_Satisfaction_Score','Marketing_Response_Rate']:
  df[i] = df[i].fillna(df[i].median())

In [22]:
for i in ['Website_Visits_Monthly','Preferred_Category','App_Sessions_Monthly','Acquisition_Channel']:
  df[i] = df[i].fillna(df[i].mode()[0])

In [23]:
df.isnull().sum()

Customer_ID                    0
Customer_Name                  0
Age                            0
Gender                         0
City_Tier                      0
Income                         0
Customer_Tenure_Months         0
Acquisition_Channel            0
Website_Visits_Monthly         0
App_Sessions_Monthly           0
Purchase_Frequency_Monthly     0
Average_Order_Value            0
Discount_Usage_Rate            0
Orders_Last_12M                0
Days_Since_Last_Purchase       0
Return_Rate                    0
Support_Tickets_12M            0
Customer_Satisfaction_Score    0
Payment_Delay_Count            0
Loyalty_Points                 0
Marketing_Response_Rate        0
Annual_Revenue                 0
Churn                          0
Purchase_Next_30_Days          0
Customer_Lifetime_Value        0
Preferred_Category             0
Preferred_Channel              0
Customer_Value_Segment         0
dtype: int64

In [24]:
X =df[['Income']] # features
y = df[['Annual_Revenue']] # target

In [27]:
import sys
import subprocess

subprocess.check_call([
    sys.executable, "-m", "pip", "install", "scikit-learn"
])

0

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [29]:
print(X_train.shape, X_test.shape)

(15000, 1) (5000, 1)

In [30]:
X_test.head()

          Income
4178    150000.0
1830   1138320.0
11207   906383.0
11038   465600.0
19630   691989.0

In [31]:
from sklearn.linear_model import LinearRegression
model_1 = LinearRegression()

In [32]:
model_1.fit(X_train, y_train)

LinearRegression()

In [33]:
y_pred = model_1.predict(X_test)

In [34]:
print(y_test,y_pred)

       Annual_Revenue
4178         44261.98
1830         78512.52
11207          500.00
11038          500.00
19630        22745.90
...               ...
15045        15026.26
13602       102144.59
5328        137238.53
3266           500.00
18484        20026.98

[5000 rows x 1 columns] [[30565.09019294]
 [61676.97187989]
 [54375.6964804 ]
 ...
 [47868.58749583]
 [30565.09019294]
 [40108.65486368]]

In [35]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred))

0.079296528025939

In [36]:
X =df[['Income','Age','Customer_Tenure_Months','Website_Visits_Monthly','Purchase_Frequency_Monthly','Average_Order_Value']] # features
y = df[['Annual_Revenue']] # target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)
model_1 = LinearRegression()
model_1.fit(X_train, y_train)
y_pred = model_1.predict(X_test)
print(r2_score(y_test, y_pred))

0.3798297429809513

In [37]:
for i in range(1, 51):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=i
    )
    model_1 = LinearRegression()
    model_1.fit(X_train, y_train)
    y_pred = model_1.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    print(i, r2)

1 0.41501658040952116
2 0.40467979048970326
3 0.39844153911546065
4 0.36451350173379515
5 0.38783624202389977
6 0.4006710080823044
7 0.40113604661481495
8 0.3855986841108644
9 0.377080741451846
10 0.3957278779728258
11 0.37569598337719023
12 0.4074006942710444
13 0.41265280080369504
14 0.37288642661771365
15 0.3950973100971119
16 0.3688820728326042
17 0.3771098361997989
18 0.4133981863659483
19 0.40091465651177693
20 0.36998974582761146
21 0.3867615474495206
22 0.3996858633437598
23 0.38688837972437773
24 0.4147477587807892
25 0.3673666837486933
26 0.37682108783476786
27 0.3874266906181283
28 0.3970661773430404
29 0.3887959949265586
30 0.3844996218316763
31 0.38901702348772005
32 0.408521055819303
33 0.4016762263801579
34 0.3541086152912951
35 0.35477129699647914
36 0.4116506681028699
37 0.3905386857682899
38 0.37561353568891764
39 0.41191338980968306
40 0.41665707024087684
41 0.39092597742822077
42 0.3743741313475344
43 0.382852549322794
44 0.4127167911016254
45 0.3887861567176536
46 0.39090551548337416
47 0.38907863018382516
48 0.4062111108891765
49 0.39231517306613917
50 0.38192073269095717

In [38]:
from sklearn.metrics import (r2_score, mean_absolute_error, mean_squared_error, f1_score, accuracy_score, classification_report)

In [39]:
print(r2_score(y_test, y_pred))
print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))

0.38192073269095717
26148.9405314759
1417756125.6936579